### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by zhang96716** [juhyeonkim95/TaxiSimulatorOnGraph#1]
I am very interested in your code, can you provide a good data set？ thank you very much

**Comment by juhyeonkim95** [comment]
First, thank you for the intereset :D
Unfortunately, the company did not allow me to disclose the data set, I cannot upload the data set not right now.
We are planning to release the dataset if we get accepted at the conference or journal.
You can still run the simple example on 10 by 10 grid.
Thank you.

**Comment by zhang96716** [comment]
Hello, I have been following your article. Congratulations on your article has been accepted. May I ask, can you publish the complete data set of this paper?

**Comment by juhyeonkim95** [comment]
Thanks for your congratulation and interest to our paper.

Unfortunately, it is decided to not upload full data because it is company's private data.
Instead, we've uploaded example data format in data_example folder, so please refer to it.
You need to use your own data to run full simulation.
For publicly available data, we uploaded full data (osmnx graph data / speed data).
